"""Criada tabela tb_profiles e adicionadas as colunas de timestamp na tb_users

Revision ID: 3d955d8b03e3
Revises: a2aab039df43
Create Date: 2022-02-07 21:52:44.001529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d955d8b03e3'
down_revision = 'a2aab039df43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tb_users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tb_users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'updated_at')
    op.drop_column('tb_users', 'created_at')
    op.drop_table('tb_profiles')
    # ### end Alembic commands ###
