"""Criada a tabela associativa tb_orders_products

Revision ID: 40db2debd3e8
Revises: db179da4a7de
Create Date: 2022-02-11 20:53:27.703277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40db2debd3e8'
down_revision = 'db179da4a7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_orders_products',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['tb_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['tb_products.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_orders_products')
    # ### end Alembic commands ###
