"""Criada tabela associativa tb_posts_tags

Revision ID: 87f54f90330a
Revises: 50d5ae50d911
Create Date: 2022-02-09 19:57:29.361595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f54f90330a'
down_revision = '50d5ae50d911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_posts_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['tb_posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tb_tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_posts_tags')
    # ### end Alembic commands ###
